### PR TITLE
Remove dis-continued DJS client options

### PR DESCRIPTION
**Pull request by Milo123459**
Removes some discontinued DJS client option properties.

### CODE REVIEW

**Comment by Milo123459** [comment]
@Katrixerse can I ask why this was closed?

**Comment by Katrixerse** [comment]
When were they discontinued this bot is in 11.6.4 not v12.

**Comment by Milo123459** [comment]
@Katrixerse In V12.

**Comment by Katrixerse** [comment]
@Milo123459 This bot doesnt use v12

**Comment by Milo123459** [comment]
That's kinda stupid ngl, it'll stop working some time in 2021

**Comment by Katrixerse** [comment]
Feel free to change it yourself if you wish to keep it working, like it says in the read me started a new bot that uses v12, so this one wont be updated to support it.

**Pull request closed without merging**
